apiVersion: v1
kind: ConfigMap
metadata:
  name: upload-service-config
  labels:
    app: upload-service
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/uploads"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
  EUREKA_INSTANCE_HOSTNAME: "upload-service"
  EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: "http://eureka-server:8761/eureka/"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  MINIO_URL: "http://minio:9000"
  MINIO_BUCKET_NAME: "uploads"