apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  init.sql: |
    CREATE DATABASE uploads;
    CREATE DATABASE frames;
    CREATE DATABASE hashes;
    CREATE DATABASE searches;
