spring:
  kafka:
    bootstrap-servers: kafka:9092
  data:
    mongodb:
      uri: mongodb://admin:secret@mongodb:27017/thoughts?authSource=admin

eureka:
  instance:
    hostname: memory-core.turron.svc.cluster.local
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8095/eureka/