spring:
  application:
    name: memory-core

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: ingestion-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer