eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}

spring:
  config:
    import: file:api-gateway/.env.dev[.properties]
