apiVersion: apps/v1
kind: Deployment
metadata:
  name: extraction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extraction-service
  template:
    metadata:
      labels:
        app: extraction-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8091"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: extraction-service
          image: ghcr.io/fl1s/turron/extraction-service:latest
          ports:
            - containerPort: 8092
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: extraction-service-config
            - secretRef:
                name: extraction-service-secret