apiVersion: v1
kind: ConfigMap
metadata:
  name: turron-config
  namespace: turron-app
data:
  EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: "http://eureka-server:8761/eureka/"
  MINIO_URL: "http://minio:9000"
  MINIO_ROOT_USER: "admin"
  MINIO_ROOT_PASSWORD: "secret123"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
  SPRING_CACHE_TYPE: "redis"
  SPRING_CACHE_REDIS_TIME_TO_LIVE: "600000"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'api-gateway'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['api-gateway.turron-app.svc.cluster.local:3000']

      - job_name: 'upload-service'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['upload-service.turron-app.svc.cluster.local:8091']

      - job_name: 'extraction-service'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['extraction-service.turron-app.svc.cluster.local:8092']

      - job_name: 'hashing-service'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['hashing-service.turron-app.svc.cluster.local:8093']

      - job_name: 'search-service'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['search-service.turron-app.svc.cluster.local:8094']