server:
  port: 8093

spring:
  application:
    name: hashing-service
  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: prometheus