apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  labels:
    app: api-gateway
data:
  SPRING_PROFILES_ACTIVE: "prod"
  EUREKA_INSTANCE_HOSTNAME: "eureka-server"
  EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: "http://eureka-server:8761/eureka/"