server:
  port: 8091

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: ingestion-service

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.serializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: prometheus