eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}

spring:
  jpa:
    properties:
      hibernate:
        dialect: ${SPRING_JPA_DATABASE_PLATFORM}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

minio:
  buckets:
    uploads: ${MINIO_BUCKETS_UPLOADS}
  url: ${MINIO_URL}
  root-user: ${MINIO_ROOT_USER}
  root-password: ${MINIO_ROOT_PASSWORD}
