eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}

spring:
  cache:
    type: ${SPRING_CACHE_TYPE}
    redis:
      time-to-live: ${SPRING_CACHE_REDIS_TIME_TO_LIVE}
  jpa:
    properties:
      hibernate:
        dialect: ${SPRING_JPA_DATABASE_PLATFORM}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

minio:
  buckets:
    uploads: ${MINIO_BUCKETS_UPLOADS}
  url: ${MINIO_URL}
  public-url: ${MINIO_PUBLIC_URL}
  root-user: ${MINIO_ROOT_USER}
  root-password: ${MINIO_ROOT_PASSWORD}
