eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}

spring:
  cache:
    type: ${SPRING_CACHE_TYPE}
    redis:
      time-to-live: ${SPRING_CACHE_REDIS_TIME_TO_LIVE}
  config:
    import: file:search-service/.env.dev[.properties]
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_PG_USERNAME}
    password: ${POSTGRES_PG_PASSWORD}
    driver-class-name: ${POSTGRES_PG_DRIVER}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

minio:
  buckets:
    uploads: ${MINIO_BUCKETS_UPLOADS}
  url: ${MINIO_URL}
  root-user: ${MINIO_ROOT_USER}
  root-password: ${MINIO_ROOT_PASSWORD}
