server:
  port: 8094

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  application:
    name: search-service
  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: prometheus