apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init-job
spec:
  template:
    spec:
      containers:
        - name: minio-init
          image: minio/mc
          envFrom:
            - secretRef:
                name: minio-secret
          command:
            - /bin/sh
            - -c
            - |
              until mc alias set myminio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD; do
                echo "Waiting for MinIO..."
                sleep 5
              done

              mc mb -p myminio/uploads || echo "uploads already exists."
              mc mb -p myminio/frames || echo "frames already exists."

      restartPolicy: OnFailure
