name: upload-service
replicaCount: 1
image:
  repository: ghcr.io/fl1s/turron/upload-service
  tag: v1.2
containerPort: 8091
metrics:
  port: 8091
resources:
  requests:
    cpu: "300m"
    memory: "384Mi"
  limits:
    cpu: "600m"
    memory: "512Mi"
service:
  port: 8091
  type: ClusterIP
secretEnabled: true
configmap:
  name: "upload-config"
  data:
    SPRING_PROFILES_ACTIVE: "prod"
    SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/uploads"
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
    SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
    EUREKA_INSTANCE_HOSTNAME: "upload-service"
    EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: "http://eureka-server:8761/eureka/"
    KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    MINIO_URL: "http://minio:9000"
    MINIO_BUCKET_NAME: "uploads"
secrets:
  SPRING_DATASOURCE_USERNAME: YWRtaW4=
  SPRING_DATASOURCE_PASSWORD: c2VjcmV0
  MINIO_ROOT_USER: YWRtaW4=
  MINIO_ROOT_PASSWORD: c2VjcmV0MTIz
