name: docker-build-push

description: Builds and pushes Docker image to GHCR

inputs:
  service:
    description: Service name
    required: true
  registry:
    description: Container registry
    default: ghcr.io
  project:
    description: Project name
    default: turron
  push:
    description: Push images to registry (true/false)
    default: 'false'
  env:
    description: Environment (dev/prod)
    default: 'dev'

runs:
  using: "composite"
  steps:
    - name: Set image tags
      shell: bash
      run: |
        echo "IMAGE_NAME=${{ inputs.registry }}/fl1s/${{ inputs.project }}/${{ inputs.service }}" >> $GITHUB_ENV
        echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
        echo "DATE_TAG=$(date +%Y%m%d)" >> $GITHUB_ENV
        if [ "${{ inputs.env }}" = "prod" ]; then
          VERSION=$(cat .config/VERSION 2>/dev/null || echo "v1.0")
          echo "VERSION_TAG=$VERSION" >> $GITHUB_ENV
        else
          echo "VERSION_TAG=dev-$SHORT_SHA" >> $GITHUB_ENV
        fi

    - name: Docker build
      shell: bash
      run: |
        cd ${{ inputs.service }}
        docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$VERSION_TAG -t $IMAGE_NAME:dev-$DATE_TAG .

    - name: Docker push
      if: ${{ inputs.push == 'true' }}
      shell: bash
      run: |
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:$VERSION_TAG
        docker push $IMAGE_NAME:dev-$DATE_TAG