apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: turron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      initContainers:
        - name: wait-for-eureka
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - 'until curl -s http://eureka:8095/eureka/apps > /dev/null; do echo "Waiting for Eureka Server..."; sleep 5; done'
      containers:
        - name: gateway
          image: ghcr.io/fl1s/gateway:latest
          ports:
            - containerPort: 3000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: turron
spec:
  selector:
    app: gateway
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort
