apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: turron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: ghcr.io/fl1s/gateway:latest
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: turron
spec:
  selector:
    app: gateway
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort
