apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-service
  namespace: turron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-service
  template:
    metadata:
      labels:
        app: ingestion-service
    spec:
      containers:
        - name: ingestion-service
          image: ghcr.io/fl1s/ingestion-service:latest
          ports:
            - containerPort: 8091
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  namespace: turron
spec:
  selector:
    app: ingestion-service
  ports:
    - port: 8091
      targetPort: 8091
