eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}

spring:
  servlet:
    multipart:
      # These properties configure the maximum allowed size for file uploads;
      # max-file-size: the maximum size of a single uploaded file;
      # max-request-size: the maximum size of the entire multipart/form-data request;
      max-file-size: 125MB
      max-request-size: 125MB
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

minio:
  bucket:
    name: ${MINIO_BUCKET_NAME}
  url: ${MINIO_URL}
  root-user: ${MINIO_ROOT_USER}
  root-password: ${MINIO_ROOT_PASSWORD}
