apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: ghcr.io/fl1s/turron/eureka-server:latest
          ports:
            - containerPort: 8761
          envFrom:
            - configMapRef:
                name: eureka-server-config