{{- if .Values.secretEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  labels:
    app: {{ .Values.name }}
type: Opaque
data:
{{ toYaml .Values.secrets | indent 2 }}
{{- end }}