apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: turron-app
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: ghcr.io/fl1s/turron/eureka-server:latest
          ports:
            - containerPort: 8761
          envFrom:
            - configMapRef:
                name: turron-config
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: EUREKA_HOSTNAME
              value: eureka-server
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 15
            periodSeconds: 20
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: turron-app
spec:
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: eureka-server
