apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: turron-app
  labels:
    app: search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: ghcr.io/fl1s/turron/search-service:latest
          ports:
            - containerPort: 8094
          envFrom:
            - configMapRef:
                name: turron-config
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/searches
            - name: EUREKA_INSTANCE_HOSTNAME
              value: search-service
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8094
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8094
            initialDelaySeconds: 15
            periodSeconds: 20
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: turron-app
spec:
  ports:
    - port: 8094
      targetPort: 8094
  selector:
    app: search-service
