apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8094"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: search-service
          image: ghcr.io/fl1s/turron/search-service:v1.2
          ports:
            - containerPort: 8094
          resources:
            requests:
              cpu: "300m"
              memory: "384Mi"
            limits:
              cpu: "600m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: search-service-config
            - secretRef:
                name: search-service-secret
      initContainers:
        - name: wait-for-eureka
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z eureka-server 8761; do
                echo "Waiting for Eureka server..."
                sleep 5
              done